### ISSUE TITLE
Race issue on cursor.next() and getMore

### ISSUE THREAD

**Issue by lchenay** [mongodb-js/mongodb-core#199]
Calling multiple time cursor.next() while current batchDocument is empty cause multiple time getMore command and throw error like:
"MongoError: clientcursor already in use? driver problem?"
"MongoError: Cursor not found, cursor id: 4338373587832"

Trying to create a simplified step to reproduce.

CF: https://github.com/Automattic/mongoose/issues/5446

**Comment by lchenay** [comment]
Simplified step to reproduce:

```javascript
exports['Should iterate cursor without race condition on next()'] = {
  metadata: {
    requires: { topology: ["single", "replicaset", "sharded"] }
  },

  test: function(configuration, test) {
    var Server = require('../../../lib/topologies/server')
      , bson = require('bson');

    // Attempt to connect
    var server = new Server({
      host: configuration.host, port: configuration.port, bson: new bson()
    });

    var ns = f("%s.cursor2", configuration.db);
    // Add event listeners
    server.on('connect', function(_server) {
      // Execute the write
      _server.insert(ns, [
        {a:1}, {a:2}, {a:3}, {a:4}, {a:5},
        {a:6}, {a:7}, {a:8}, {a:9}, {a:10}
        ], {
        writeConcern: {w:1}, ordered:true
      }, function(err, results) {
        test.equal(null, err);

        // Execute find
        var cursor = _server.cursor(ns, {
          find: ns
          , query: {}
          , batchSize: 5
        });

        var async = require('async');
        async.times(5, function(n, next) {
          cursor.next(next);
        }, function(err) {
          test.equal(null, err);
          async.times(5, function(n, next) {
              cursor.next(next);
          }, function(err) {
            test.equal(null, err);
            // Destroy the server connection
            _server.destroy();
            // Finish the test
            test.done();
          });
        });
      });
    });

    // Start connection
    server.connect();
  }
};
```

**Comment by lchenay** [comment]
Ugly workaround to better understand ; at least it fix the problem.
https://github.com/christkv/mongodb-core/compare/2.0...lchenay:patch-1

**Comment by mahnunchik** [comment]
Any news?

**Comment by teddis** [comment]
I'm getting "MongoError: cursor id not found" a lot and it's distressing. I'm trying to step through only 20,000 documents and my loop periodically dies from this and I have to restart from that point forward using skip to continue from the point of death. Pretty bad. I'm sorry I don't have the patience to post more info right now, but can later if desired. Using Node 8.5.0, Mongoose 5.0.10 and Mongo 3.6.2, default heap.

**Comment by mbroadst** [comment]
@teddis please file a bug report on our JIRA, thank you.

**Comment by mbroadst** [comment]
@cosminn777 please file a bug report on our [JIRA](https://jira.mongodb.org/browse/NODE), thank you.

**Comment by dandv** [comment]
Also getting `MongoError: cursor id ... is already in use` randomly, and I'm not sure how I can file a meaningful bug report on JIRA without sharing my collection. The code is

```
const cursor = collection.find({ createdAt: { $lt: new Date() } });
do {
  // ...
  const bulk = collection.initializeOrderedBulkOp();
  for (const item of itemsToUpdate)
    bulk.find({ _id: item._id }).replaceOne(item);
  const result = await bulk.execute();
} while (cursor.hasNext());

**Comment by mbroadst** [comment]
@dandv it looks like you need to be doing `} while (await cursor.hasNext())`

**Comment by dandv** [comment]
@mbroadst: After adding `await`, I still see a related error in a similar loop, if processing takes longer than ~10 minutes:

> MongoError: cursor id 40280262609 not found

```js
const cursor = await users.find(
  { },
  {
    projection: { ... },
  }
).batchSize(100 * 100);
 
let user = await cursor.next();
while (user) {
  const usersInDb = { };
  // Get up to PAGE_SIZE users (<PAGE_SIZE at the end of the cursor)
  for (let i = 0; i < PAGE_SIZE && user; i++, user = await cursor.next())
    usersInDb[user._id] = user;
 
  // Process users...
  // ...
  const bulk = users.initializeUnorderedBulkOp();
  // ...
  bulk.find({ _id: id }).updateOne(userUpdateForDb);
 
  // Update users
  try {
    await bulk.execute();
  } catch (error) {
    ...
  }
}
```

The collection has ~65,000 documents, and I've reduced the batch size to 10,000 per [this SO question](https://stackoverflow.com/questions/44248108/mongodb-error-getmore-command-failed-cursor-not-found/44250410#44250410) in order to keep the cursor alive.

**Comment by mbroadst** [comment]
@dandv have you tried disabling the cursor timeout? Also, would you mind creating a jira ticket for your issue? We try as much as possible to make that our single source of truth for driver bugs these days.

**Comment by dandv** [comment]
Sorry, forgot to include the link to [the JIRA ticket](https://jira.mongodb.org/browse/SERVER-24899?focusedCommentId=2261638).

Haven't tried disabling the cursor timeout because it didn't seem necessary - according to the explanations in [that SO answer](https://stackoverflow.com/questions/44248108/mongodb-error-getmore-command-failed-cursor-not-found/44250410#44250410), a smaller batchSize would keep the cursor alive as the client requests more documents from it. Traversing the whole collection of 65k documents took ~20 minutes, so with a batchSize of 1000, I expected the cursor to be pinged every about 20 seconds.
