### ISSUE TITLE
Can round-robin connection pool logic be smarter?

### ISSUE THREAD

**Issue by bompus** [mongodb-js/mongodb-core#213]
Currently, as I read it and have tested, it appears that the pool logic is doing a simple round robin approach. This works well if you don't have a mix of slow and fast queries.

When you have some slow queries, you can easily end up with many fast queries stuck behind a connection that is processing a slow query.

It appears there is already support for the pool to grow to a maximum size of connections, but even using a large connection pool max size doesn't solve the problem. If you have hundreds or thousands of queries or commands executing, at some point, you will still get backed up unnecessarily behind a slow query, regardless of whether you have a max pool size of 10 or 100.

Would it be possible to refactor the pool mechanics to queue up items to the connection with the lowest amount of commands queued up?

You'd probably have to maintain a count of pending commands for each connection, but I believe the benefit would be substantial for anybody who is using the driver with a connection pool > 1 and has a mix of slow and fast queries.

Thank you for considering my suggestion!

**Comment by mbroadst** [comment]
@bompus sounds like a very interesting idea! Unfortunately we are in a push right now to get 3.6 features out the door, so I don't suspect there will be any active work on this, but I would love to collaborate and would definitely be willing to review any contributions you might have in the meantime.

**Comment by bompus** [comment]
@mbroadst It's been a while, but I think this is still relevant. Submitted a PR.

**Comment by Ijmir** [comment]
+1

**Comment by mbroadst** [comment]
Hey @bompus and @Ijmir, we've completely redesigned the connection pool and will be merging it in shortly (see this PR for the initial steps: https://github.com/mongodb/node-mongodb-native/pull/2047). This project has been merged into the main driver, and will soon be outright deprecated. I'm disabling GitHub issues within the week, so please reach out to us through JIRA for further discussion if the new pool design doesn't address your needs.
