### ISSUE TITLE
Vulnerable module: bson

### ISSUE THREAD

**Issue by ChristopheBraud** [mongodb-js/mongodb-core#281]
Hi,

There is a low severity issue with bson dependency

https://snyk.io/test/npm/mongodb/3.0.3?severity=high&severity=medium&severity=low
https://snyk.io/test/npm/bson/1.0.4?severity=high&severity=medium&severity=low

Please, update bson to 2.0.0 or above.

**Comment by mbroadst** [comment]
Hi @ChristopheBraud, the fix was actually made for v1.0.5 and v2.0.0 of bson, and mongodb-core is pegged at `~1.0.4` which will bring in the fix. I've alerted snyk to update their information, as it is incorrect. Thanks for the heads up.
