### ISSUE TITLE
Feature request: allow passing Duplex stream for underlying TCP connection

### ISSUE THREAD

**Issue by mscdex** [mongodb-js/mongodb-core#282]
It's very useful when database drivers allow a Duplex stream as the underlying connection instead of being forced to create a local socket. One major use case for this is being able to easily access a database over an SSH connection. With a module like `ssh2`, we can obtain a Duplex stream that represents a forwarded TCP connection and not have to bind to a local socket for connection forwarding.

**Comment by mbroadst** [comment]
@mscdex do you mean you'd like a way to bypass the entire connection pool, and connect stages, and simply tell the driver to use some socket you've previously set up?

**Comment by mscdex** [comment]
Yes. Perhaps the pool could still be used by providing some callback when a new connection is needed. For example:

```js
// no pool, just single connection
db.connect({ /*...,*/ stream: duplexStream })

// pool, async connection setup
db.connect({
  /*...,*/
  createConnection: (cb) => {
    // do some async stuff here
    cb(null, duplexStream);
    // or if not able to create a stream
    cb(someError);
  }
);
```

**Comment by mbroadst** [comment]
@mscdex yeah, I like the second approach there. We're actually gong to be doing a full refactor of SDAM this quarter, and subsequently a Pool rewrite - is this a priority at all for you?

**Comment by mscdex** [comment]
Not for me, no, but I see the scenario pop up from time to time on issue trackers, stackoverflow, and the like. I can point MySQL users to the `mysql2` module, which can accept a stream object. Mongodb seems to be the second most common database being mentioned when tunneling database connections.

**Comment by mbroadst** [comment]
Hi @mscdex, I've created [NODE-2026](https://jira.mongodb.org/browse/NODE-2036) to track this. We are in the process of migrating to a new pool implementation where I could imagine this being much easier to implement. Also, this project has been merged into the main driver, and is now deprecated. I'll be closing this issue, and soon outright disabling GitHub issues. Please reach out to us through JIRA for further questions/concerns/suggestions. Thanks!
