### ISSUE TITLE
Detected use of sync API for nonce var in scram auth

### ISSUE THREAD

**Issue by jcallu** [mongodb-js/mongodb-core#285]
(node:39601) WARNING: Detected use of sync API
    at executeScram (./node_modules/mongodb-core/lib/auth/scram.js:133:24)
    at ./node_modules/mongodb-core/lib/auth/scram.js:299:7
    at _combinedTickCallback (internal/process/next_tick.js:131:7)

`

var nonce = crypto.randomBytes(24).toString('base64');

**// could we change to**
crypto.randomBytes(24, function(err, nonceBuffer) {
  var nonce = nonceBuffer.toString('base64');
})

`

**Comment by mbroadst** [comment]
@jcallu yes that is possible, however it would have to be a far more involved refactor of the scram auth code, such that the callback to authenticate is called from within the callback to `randomBytes`. This is unlikely to be high priority for us, but a pull request would be welcomed.
