### ISSUE TITLE
connection increase problem

### ISSUE THREAD

**Issue by tiger-cub** [mongodb-js/mongodb-core#292]
I set the connection pool size to 5 and ran the application.
Restarting db will continue to increase the number of connections to mongo db up to unlimit..
i found 8000 connection count when application was down.
Most connections are in keepalive state.

set the version 3.0.1 to 3.0.6..... make problem
but use 2.1.19 cannot make problem. what's different?

**Comment by yg-dev** [comment]
@menme95 no! 2.1.19 has no problem. so i using that now.

**Comment by menme95** [comment]
I've test the version 5.2.9 and it has been solved, if you want to update a newer version.
