### ISSUE TITLE
Ability for collection to map ALL documents for every method in one call.

### ISSUE THREAD

**Issue by j** [mongodb-js/mongodb-core#301]
I'm creating a library to map plain document objects to classes I want to refrain from having to create my own collection wrapper.

I.E.)

```typescript
import { documentToClass } from './mapper';

@Document()
class User {
    @Field()
    firstName: string;

    @Field()
    lastName: string;
}

const collection = db.collection('users', {
    map: (doc: any): User {
        return documentToClass(User, doc);
    }
});

// collection.find() // internally cursor sets map to above
// collection.findOne() // returns User
// collection.updateOne() // returns User
// collection.findOneAndUpdate() // returns User
// .... etc, etc... anything that returns a document(s), gets mapped to User | User[]
```

Is this possible in the current state?

**Comment by daprahamian** [comment]
@j Can you use [Cursor.prototype.map](http://mongodb.github.io/node-mongodb-native/3.0/api/Cursor.html#map)?

**Comment by daprahamian** [comment]
`collection.find` returns a `Cursor`. See [here](http://mongodb.github.io/node-mongodb-native/3.0/api/Collection.html#find).

There is currently no stable way to pass a transform in to the collection constructor and have it apply to all cursors.

**Comment by daprahamian** [comment]
In that case, could you please file a JIRA ticket [here](https://jira.mongodb.org/browse/NODE) with your feature request?
