### ISSUE TITLE
"MongoError":"no mongos proxy available"

### ISSUE THREAD

**Issue by sumanth10** [mongodb-js/mongodb-core#302]
Hello,
 I have been using MongoDB node driver with version 3.0.7 to connect to compose MongoDB. But I am unable to connect to the DB since its throwing **no mongos proxy available error**. I have posted the code i am using to connect to the mongoDB . Thanks in advance

```
    MongoClient.connect(config.url, function(err,database) {
        if(err && err.error != "file_exists"){
                    console.log("Error creating Database"+JSON.stringify(err));
                    throw err; 
                }else{
                    console.log("Connected correctly to server");
                    dbConnect = database.db(config.db);
                    callback();
                }
       
    });

**Comment by daprahamian** [comment]
@sumanth10 can you please file a JIRA ticket and specify your issue? Thanks.
