### ISSUE TITLE
MongoError is instanceof Error

### ISSUE THREAD

**Issue by oliverm2112** [mongodb-js/mongodb-core#304]
Shouldn't a MongoError resolve to an instanceof MongoError? Its current (mongodb-core 3.0.7) __proto__ and instanceof is Error.

I'm writing an error handler that is trying to identify the type of error.

`err instanceof MongoError === false`
Should be:
`err instanceof MongoError === true`

**Comment by daprahamian** [comment]
@oliverm2112 I cannot reproduce the results you are seeing.

I've run the following on node `4.9.1`, `6.14.1`, `8.11.1`:
```js
'use strict';

const mongodb = require('mongodb');
const core = require('mongodb-core');

const MongoError = mongodb.MongoError;
const CoreMongoError = core.MongoError;

const x = new MongoError('foo');
const y = new CoreMongoError('bar');

console.log(`x instanceof Error: ${x instanceof Error}`);
console.log(`x instanceof MongoError: ${x instanceof MongoError}`);
console.log(`x instanceof CoreMongoError: ${x instanceof CoreMongoError}`);
console.log(`y instanceof Error: ${y instanceof Error}`);
console.log(`y instanceof MongoError: ${y instanceof MongoError}`);
console.log(`y instanceof CoreMongoError: ${y instanceof CoreMongoError}`);
```

The output:
```
x instanceof Error: true
x instanceof MongoError: true
x instanceof CoreMongoError: true
y instanceof Error: true
y instanceof MongoError: true
y instanceof CoreMongoError: true
```

Is it possible that you have two instances of `mongodb-core` that are conflicting with each other?

**Comment by oliverm2112** [comment]
I think I found what it was - I was using MongoError from mongodb-core 3.0.1 in one place and from mongo-db 3.0.7 in a module. Everything is working fine now. Thanks @daprahamian
