### ISSUE TITLE
Question: Is there a single source that gets a document (or documents) only passed to it?

### ISSUE THREAD

**Issue by j** [mongodb-js/mongodb-core#305]
I'm trying to add document mapping into either core, bson, or the mongodb driver.  I'm going through the code and it seems there isn't a single area that accepts a "document" or "documents" as an argument.  BSON serialization seems to serialize more than the document itself, but the entire command.  Is there a specific shape of results, or an area where I can determine exactly where the documents are to add mapping?

**Comment by mbroadst** [comment]
Hi, this project has now been merged into the main driver and is therefore deprecated. Please open a JIRA ticket for this issue if it is still relevant.
