### ISSUE TITLE
new release?

### ISSUE THREAD

**Issue by simllll** [mongodb-js/mongodb-core#306]
I'm still running into troubles regarding the https://jira.mongodb.org/projects/NODE/issues/NODE-1420 issue. It is already fixed, but not included in the latest release.

Is there a plan for a new release?

thanks
Simon

**Comment by daprahamian** [comment]
@simllll I'll try to get out a release later today

**Comment by daprahamian** [comment]
`3.0.8` and `3.1.0-beta3` published for `mongodb-core` and `mongodb`
