### ISSUE TITLE
TypeError: utf8 is not a function

### ISSUE THREAD

**Issue by vishalgakhare** [mongodb-js/mongodb-core#330]
I'm upgrading mongoose from 4.7.x to 5.2.x. I'm getting the error that points to mongodb-core, on starting up the node app:

```javascript
ode_modules/mongoose/node_modules/mongodb-core/lib/auth/scram.js:189
      Buffer.from('n=', 'utf8'),
             ^

TypeError: utf8 is not a function
    at Function.from (native)
    at Function.from (native)
    at executeScram (/Users/user/Repos/App/node_modules/mongoose/node_modules/mongodb-core/lib/auth/scram.js:189:14)
    at /Users/user/Repos/App/node_modules/mongoose/node_modules/mongodb-core/lib/auth/scram.js:361:7
    at nextTickCallbackWith0Args (node.js:419:9)
    at process._tickDomainCallback (node.js:389:13)`
```

If I need to change anything in the mongoose then I'd have gotten error in mongoose. What do you think is wrong?

"mongoose": "5.2.0"
node v4.3.0

**Comment by daprahamian** [comment]
Hi @vishalgakhare,

Your error results from using node `4.3.0`. In general, we support the latest lts versions of node. For node 4, that would be Node 4.9.1.

Are you capable of upgrading to Node 4.9.1?

- Dan

**Comment by vishalgakhare** [comment]
Using nvm I switched nodeJS to 5.0.0 and still faced the error (slightly different stack trace). 
```javascript
at doNTCallback0 (node.js:428:9)
    at process._tickDomainCallback (node.js:398:13)
```
Then I switched to 4.9.1 and the issue resolved. Weird.
