### ISSUE TITLE
$geoNear, $near, and $nearSphere are not allowed in this context

### ISSUE THREAD

**Issue by Polqk** [mongodb-js/mongodb-core#349]
Hi,
After mongoose, mongodb update i have an error message with $near, I don't know if it mongodb or mongoose problem, before update it's work fine, thanks for help

api : 
![near](https://user-images.githubusercontent.com/36846411/45107055-a8053a80-b138-11e8-8890-a5b7f61646a0.png)

client : 
![near2](https://user-images.githubusercontent.com/36846411/45107065-b2273900-b138-11e8-8abf-6483d0c2b315.png)

client code : 
![near3](https://user-images.githubusercontent.com/36846411/45107080-bb180a80-b138-11e8-8cd3-c97256425ffd.png)

**Comment by mbroadst** [comment]
Hi @Polqk, can you please open a JIRA ticket for this [here](https://jira.mongodb.org/projects/NODE)? Also please include more of your client code, specific to what operation you are trying to pass this query into. Is it an aggregation? count? find? Thanks!
