### ISSUE TITLE
Auth issues with version 3.1.9

### ISSUE THREAD

**Issue by HRK44** [mongodb-js/mongodb-core#381]
Please see : https://github.com/Automattic/mongoose/issues/7270

I think it's related to your new code about parsing auth/connection string.

> uri_parser: uri-encoded auth handling (81b5b45)

**Comment by HRK44** [comment]
I found a work around, I removed the DB name from the connection string :
``DB_HOST=mongodb://mongodb:27017/mydb`` -> ``DB_HOST=mongodb://mongodb:27017`` and I set up the **optional** ``dbName`` attribute in the mongoose connection params to ``mydb``.

Is this behavior actually wanted?

**Comment by mbroadst** [comment]
@HRK44 the commit you're pointing to only affects `mongodb+srv` connection strings. I suspect the issue you are running into is [in this change|https://github.com/mongodb/node-mongodb-native/commit/c7dec28513050d5e31374208d1f41f72d2f57e87]. Can you try removing that code and seeing if you are still affected?

Also, please use our JIRA for future tickets.

**Comment by HRK44** [comment]
@mbroadst I think you are right this commit is the culprit - it works fine after commenting this piece of code, I'll create an issue on JIRA referencing https://github.com/mongodb/node-mongodb-native/commit/c7dec28513050d5e31374208d1f41f72d2f57e87. Thanks for pointing this out

**Comment by HRK44** [comment]
https://jira.mongodb.org/browse/NODE-1772 issue created here.
