### ISSUE TITLE
Connection meta data lost in connection pool

### ISSUE THREAD

**Issue by marekkajda** [mongodb-js/mongodb-core#388]
Hi Guys,

I connect to my MongoDb from different micro services and have a problem with too many connections opened even when I have limited connection poll for each micro service.

My problem to investigate that issue is with recognize the author of connections listed in db.currentOp(true). I set extra meta data for the connection (as appName, driver, os etc.) but it looks like it's saved only for the main/first connection and the rest of connections created for the application poll are missing that data.

Example of the main connection:
`{
    "desc" : "conn22600",
    "threadId" : "139670253233920",
    "connectionId" : 22600,
    "client" : "xx.xx.xx.38:24523",
    "appName" : "middleware_1.18.928.13_linux_1_organisation_2018-12-04T17:14:43.542Z",
    "clientMetadata" : {
        "driver" : {
            "name" : "nodejs",
            "version" : "2.2.33"
        },
        "os" : {
            "type" : "Linux",
            "name" : "linux",
            "architecture" : "x64",
            "version" : "4.4.115-k8s"
        },
        "platform" : "Node.js v10.5.0, LE, mongodb-core: 2.1.17",
        "application" : {
            "name" : "middleware_1.18.928.13_linux_1_organisation_2018-12-04T17:14:43.542Z"
        }
    },
    "active" : false
}`
Example of the connection created from connection poll:
`{
    "desc" : "conn22833",
    "threadId" : "139670411134720",
    "connectionId" : 22833,
    "client" : "xx.xx.xx.38:13774",
    "active" : false
}`

Is it possible to replicate meta data for all connections? For now I can't even find a parent connection.

Thanks,
Marek

**Comment by mbroadst** [comment]
Hi @marekkajda, sorry for the delayed response. This is indeed a bug in our handshake implementation, thanks for identifying it. We are in the process of rewriting the connection pool and this is a specified part of that process, but I still made a ticket you can track [here](https://jira.mongodb.org/browse/NODE-1806). I'm going to close this ticket now, please follow that ticket from here out.
