### ISSUE TITLE
Logging query execution time

### ISSUE THREAD

**Issue by marekkajda** [mongodb-js/mongodb-core#397]
Hi Guys,

I hope it isn't a stupid question, but can't find the solution anywhere. Is there a simple way to log stats of all queries made to MongoDb? I use MongoDb with NodeJS/Express and want to log Middleware request time and how much time was spent requesting db. Are there any global events for singular queries?

Thanks,
Marek

**Comment by daprahamian** [comment]
Hi @marekkajda,

Not a stupid question at all. A good way to do this is to enable commandMonitoring at the `MongoClient` level.

```js
// Pass the "monitorCommands" flag to your MongoClient
const client = new MongoClient('url', { ..., monitorCommands: true });

// Subscribe to the commandMonitoring events
// - commandStarted will fire when a command is sent to the server
// - commandSucceeded will fire when the response comes back and doesn't have an error
// - commandFailed will fire when the response comes back with an error
client.on('commandStarted', e => console.log(e));
client.on('commandSucceeded', e => console.log(e));
client.on('commandFailed', e => console.log(e));
```

In the future, you can ask questions like this on our JIRA by following the steps [here](https://github.com/mongodb-js/mongodb-core#bugs--feature-requests).

**Comment by daprahamian** [comment]
Filed https://jira.mongodb.org/browse/NODE-1853 to update our documentation regarding our APM API.
