### ISSUE TITLE
mongoerror not propagated with raw queries

### ISSUE THREAD

**Issue by timkuijsten** [mongodb-js/mongodb-core#420]
When a raw query yields an error, the message and code get lost because the raw buffer object is passed to MongoError.create. A partial solution that deserializes the document before calling MongoError.create can be seen here: https://github.com/timkuijsten/mongodb-core/commit/3c30652c65f9e6ae2dca2b75284e6d3fdcdde4fe.

I have only tested with version 2.1.19 but assume the same problem exists in master at the time of this writing: https://github.com/mongodb-js/mongodb-core/blob/f88da4efb7912edbb861476a6e007f388d16c1c6/lib/cursor.js#L666

**Comment by kvwalker** [comment]
Hi @timkuijsten, thanks for the partial solution! Could you provide your test script and/or test this with master? Version 2.x is no longer supported so it's possible that this changed.

**Comment by timkuijsten** [comment]
Unfortunately I currently don't have the time to do this. Please feel free to close this issue.
