### ISSUE TITLE
Issue into ScramSHA256._executeScram

### ISSUE THREAD

**Issue by Fred2MTL** [mongodb-js/mongodb-core#426]
Hi All,

I use Mongo (4.0.8) and Express (4.16.4) / Mongoose (5.5.2) / MongoDb (3.2.2, as dependency of Mongoose, or 3.2.3, directly) on on Node 11.14. I rebuild the instance (including the authentication / autorization part) and reload the data from the CLI. 

I can access to the data correctly from Compass or MongoHub. But, I encounter the following issue during the 'preparation of the password' with Mongoose or MongoDb (both of them):
```javascript
xXx/node_modules/saslprep/index.js:41
    throw new TypeError('Expected string.')
    ^

TypeError: Expected string.
    at saslprep (xXx/node_modules/saslprep/index.js:41:11)
    at ScramSHA256._executeScram (xXx/node_modules/mongoose/node_modules/mongodb-core/lib/auth/scram.js:144:38)
    at AsyncWrap.crypto.randomBytes (xXx/node_modules/mongoose/node_modules/mongodb-core/lib/auth/scram.js:239:19)
    at AsyncWrap.wrap.ondone (internal/crypto/random.js:57:8)
```
to validate the case, I try to connect by using Mongooose or Mongdob (directly) by using the correct URL (mongodb://localhost:27017/admin) with the appropriate parameter set:
- mongoDb: {auth:{user,password}, ...}
- mongoose:{user,pass, ...}

I obtain the same issue in both cases.

The trace on the engine shows the connection establishment, then its close:
```
2019-04-20T07:56:01.374-0400 I NETWORK  [conn1] received client metadata from 127.0.0.1:53074 conn1: { driver: { name: "nodejs", version: "3.2.2" }, os: { type: "Darwin", name: "darwin", architecture: "x64", version: "18.5.0" }, platform: "Node.js v11.14.0, LE, mongodb-core: 3.2.2" }
2019-04-20T07:56:01.390-0400 I NETWORK  [conn1] end connection 127.0.0.1:53074 (0 connections now open)
```

So, I need some help to determine if I miss something or it's a potential bug.

Thanks in advance

Fred

**Comment by mbroadst** [comment]
Hi @Fred2MTL, my guess is that your password is `undefined` or `null` by the time `saslprep` is trying to process it. You can immediately verify this by printing out the password at the `saslprep` callsite (`xXx/node_modules/mongoose/node_modules/mongodb-core/lib/auth/scram.js:144`). If that's indeed the case, could you please provide your actual `MongoClient` constructor call? This might be an issue with the options themselves.

**Comment by Fred2MTL** [comment]
Hi @mbroadst 
Thanks for your answer. But, no. The password is valued and propagated into the call stack (see below).

According to the previous stacktrace, I add some traces into the files scram.js and saslprep.index.js as following:
```javascript
scram.js
 _executeScram(sendAuthCommand, connection, credentials, nonce, callback) {
    let username = credentials.username;
    const password = credentials.password;
    const db = credentials.source;
    _console.log(credentials);_
    const cryptoMethod = this.cryptoMethod;
    let mechanism = 'SCRAM-SHA-1';
    let processedPassword;

    if (cryptoMethod === 'sha256') {
      mechanism = 'SCRAM-SHA-256';
      _console.log(`password: ${password}`);_
      processedPassword = saslprep ? saslprep(password) : password;
    } else {
      try {
        processedPassword = passwordDigest(username, password);
      } catch (e) {
        return callback(e);
      }
    }

index.js
 function saslprep(input, opts = {}) {
  if (typeof input !== 'string') {
    throw new TypeError('Expected string.')
  }

  if (input.length === 0) {
    return ''
  }
  _console.log(`input: ${input}`);_
  // 1. Map
  const mapped_input = input
    .split('')
    .map(getCodePoint)
    // 1.1 mapping to space
    .map(character => (mapping2space.get(character) ? 0x20 : character))
    // 1.2 mapping to nothing
    .filter(character => !mapping2nothing.get(character))
  _console.log(`mapped_input: ${mapped_input}`);_
  // 2. Normalize
  const normalized_input = String.fromCodePoint(...mapped_input).normalize('NFKC')
  _console.log(`normalized_input: ${normalized_input}`);_
  const normalized_map = normalized_input.split('').map(getCodePoint)
```
Then, i obtain the following traces, showing the password is well propagated and the normalization fails: 
```javascript
xXx/node_modules/saslprep/index.js:60
  const normalized_map = normalized_input.split('').map(getCodePoint)
                                          ^

TypeError: Cannot read property 'split' of undefined
    at saslprep (xXx/node_modules/saslprep/index.js:60:43)
    at ScramSHA256._executeScram (xXx/node_modules/mongodb-core/lib/auth/scram.js:144:38)
    at AsyncWrap.<anonymous> (xXx/node_modules/mongodb-core/lib/auth/scram.js:239:19)
    at AsyncWrap.wrap.ondone (internal/crypto/random.js:59:8)
MongoCredentials {
  username: 'panelServer',
  password: 'Dt[v121Ogyf9E89.',
  source: 'admin',
  mechanism: 'scram-sha-256',
  mechanismProperties: undefined
}
password: Dt[v121Ogyf9E89.
input: Dt[v121Ogyf9E89.
mapped_input: 68,116,91,118,49,50,49,79,103,121,102,57,69,56,57,46
normalized_input: undefined
```

**Comment by daprahamian** [comment]
hi @Fred2MTL,

I'm not able to replicate your bug by directly passing your password into `saslprep`:

```js
const saslprep = require('saslprep');
const input = 'Dt[v121Ogyf9E89.';
const output = saslprep(input);
console.log(output); // Dt[v121Ogyf9E89.
```

Can you reproduce this?

\- Dan

**Comment by Fred2MTL** [comment]
Hi Dan
I did it. So, the issue came from an old library, integrating a unused version of String.prototype.normalize. Some changes had driven this prototype to be used instead of the official one, specified and implemented by Node. I've deleted it and this issue is solved now.
Thanks for your support
Fred
