### ISSUE TITLE
Cursor topology lacks the host and port, while Server topology has it

### ISSUE THREAD

**Issue by duro** [mongodb-js/mongodb-core#428]
Not sure if this was an intentional design choice, but the `topology.s.options` object in the Cursor "class" does not have a host or port key, while the Server class does.

In efforts to wrap the mongo driver for trace instrumentation (with AWS X-Ray in my case) a minimal amount of monkey patching was needed around these two "classes". I began diving into them and noticed the difference.

If this is intentional, I'm curious why? And if not, might be nice to get those two props in there, as monkey patching the driver like this is pretty much the common practice for adding trace instrumentation.

**Comment by kvwalker** [comment]
Hi @duro, it looks like `topology.s.options` does have both `host` and `port`. If you're not seeing those, could you provide the code you're using?

**Comment by duro** [comment]
@kvwalker Here is the script I'm writing to monkey patch some of the mongo-db core methods to implement x-ray tracing:

https://gist.github.com/duro/a5ad70a40879f3ffc92986ccc7a4c503

If you scroll down to L107 you'll see where I'm trying to access those properties.

L27 and 54 are where I pass in what eventually is referenced in L107.

So for the Server object, it's `this.s.options`, and for Cursor it's `this.topology.s.options`

I did a debug session, and console logged out those cobject paths, and I can clearly see that the Server has a host/port and Cursor does not.

The gist above also includes these console logs

Not sure if this matters, but I am hitting a cluster that has replica set.

Also, I'm getting mongodb-core via mongoose, and it's running version `3.1.11`

**Comment by kvwalker** [comment]
Thanks for providing more information. These are internal properties so we don't support monkey patching like this. If you'd like to request top level API for properties that you need, you can file a ticket in our [Jira project](https://jira.mongodb.org/projects/NODE).
