### ISSUE TITLE
Unable to find cursor with id using CosmosDB Microsoft Azure database, SSL on

### ISSUE THREAD

**Issue by antoinegomez** [mongodb-js/mongodb-core#432]
Version with error tested: `3.2.0, 3.2.1, 3.2.2`

Version that works tested: `3.1.13`

nodejs version: `v10.5`

**Error stack:**

```
MongoError: Unable to find cursor with id: 1
    at Connection.<anonymous> (/workspace/antoine/mongotest/node_modules/mongodb-core/lib/connection/pool.js:443:61)
    at Connection.emit (events.js:182:13)
    at processMessage (/workspace/antoine/mongotest/node_modules/mongodb-core/lib/connection/connection.js:364:10)
    at TLSSocket.<anonymous> (/workspace/antoine/mongotest/node_modules/mongodb-core/lib/connection/connection.js:533:15)
    at TLSSocket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at TLSSocket.Readable.push (_stream_readable.js:219:10)
    at TLSWrap.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
```

**how to reproduce?**

- Create a cosmosdb database with one collection with partitioning activated
- One shard_key per collection, e.g.: shard key field name -> shard_key
- Insert/update documents, at least 101 documents
- Find documents

If you only find documents there is no error.

I tested with less than 100 documents and there was no error. So this is really a cursor problem, once we need to fetch more results the query fails.

[Code to reproduce the error](https://github.com/antoinegomez/mongodb-core-cosmosdb-cursor-error)

**Comment by kvwalker** [comment]
Hi @antoinogomez, are you able to reproduce this error against a real MongoDB instance?

You might not be aware of this, but CosmosDB only emulates MongoDB and therefore suffers from these types of bugs and inconsistencies. Unfortunately, we do not support CosmosDB, so we will not be fixing this cursor problem unless it is actually a bug in MongoDB.

Have you heard of Atlas? It's our database-as-a-service, similar to CosmosDB but backed by real MongoDB servers. You can try to reproduce this bug against Atlas if you'd like and we can provide you with credits to test for free.

Please let me know if you'd like to try Atlas and I will send you the promo code!

**Comment by antoinegomez** [comment]
@kvwalker OK I understand your position and I am willing to get the free credits to try to reproduce on Atlas. Thank you.

**Comment by kvwalker** [comment]
Great! The code is REALMONGO.

**Comment by antoinegomez** [comment]
It's of course working fine with MongoDB Atlas, I was not expecting to have any problems. I will try to contact and escalate this issue to the CosmosDB team.
