### ISSUE TITLE
When cursorId is already a Long, don't call FromNumber

### ISSUE THREAD

**Issue by jasontho-ms** [mongodb-js/mongodb-core#440]
Commit [14b597bc6604e1b7ec69ae786619e979](https://github.com/mongodb-js/mongodb-core/commit/e7e1775fc5175a331ff06bcba543c09285462ffe#diff-14b597bc6604e1b7ec69ae786619e979) introduced an issue:

When the cursorId is already a large-valued Long, calling fromNumber with it will truncate it. This is tested for in other places but not on the lines added by the commit above.

**Comment by daprahamian** [comment]
Closed by #441
