### ISSUE TITLE
Cannot connect mongodb with same mongos url

### ISSUE THREAD

**Issue by CodingJun** [mongodb-js/mongodb-core#442]
https://github.com/mongodb-js/mongodb-core/blob/cc26b16380ef02543e1000dda3fa639cb64fcd19/lib/topologies/mongos.js#L351

the connect url like mongodb://localhost:27017,localhost:27017/admin
it's normal in version 3.1，but now i get no error and no connect

**Comment by mbroadst** [comment]
Hi @CodingJun. `mongodb-core` has been merged into the main driver as of the upcoming 3.3.0 release. Please file a JIRA ticket with more details about what type of issue you are running into with the driver.
