### ISSUE TITLE
Prevent Critical Dependency Warnings When Bundling MongoDb using ES Modules and Webpack

### ISSUE THREAD

**Issue by Lonniebiz** [mongodb-js/mongodb-core#444]
I use webpack 4.25.0 to bundle mongodb 3.2.7 into a node.js 10.16.0 app. The bundle works fine, but each time I build I have to see these warnings:

```
WARNING in ./node_modules/require_optional/index.js 82:18-42
Critical dependency: the request of a dependency is an expression
 @ ./node_modules/mongodb-core/index.js
 @ ./node_modules/mongodb/index.js
 @ ./src/utility/mongo.mjs
 @ ./src/server.js

WARNING in ./node_modules/require_optional/index.js 90:20-44
Critical dependency: the request of a dependency is an expression
 @ ./node_modules/mongodb-core/index.js
 @ ./node_modules/mongodb/index.js
 @ ./src/utility/mongo.mjs
 @ ./src/server.js

WARNING in ./node_modules/require_optional/index.js 97:35-67
Critical dependency: the request of a dependency is an expression
 @ ./node_modules/mongodb-core/index.js
 @ ./node_modules/mongodb/index.js
 @ ./src/utility/mongo.mjs
 @ ./src/server.js
```
This may have something to do with the fact that I use Ecmascript Modules instead of Common.js modules to import the mongodb package; my mongo.mjs file starts like this:

```
import { default as mongodb } from 'mongodb';
const MongoClient = mongodb.MongoClient;
```

To avoid seeing these warnings on every build, I've added an object to my webpack.config.js file that looks like this:

```
let wp = {}; wp.stats = {}; wp.stats.warningsFilter = (warning)=>
{
	let aryModulesToBlockWarningsFrom =
	[
		"node_modules/require_optional/index.js"
	];

	let block = false;
	aryModulesToBlockWarningsFrom.forEach((modulePath)=>
	{
		if(RegExp(modulePath).test(warning) === true)
		{
			block = true;
		}
	});
	return block;
};
```

Also submitted this bug to require_optional [here](https://github.com/christkv/require_optional/issues/10). I also have this [same issue](https://github.com/webpack/webpack/issues/1576) when I bundle express using ES Modules and Webpack.

**Comment by mbroadst** [comment]
Hi @Lonniebiz, can you please open a [JIRA ticket](https://jira.mongodb.com/projects/NODE) for this issue? This project has been merged into the main driver, and will be deprecated in an upcoming v3.3.0 release. GitHub issues will be closed when that release is made.

**Comment by Lonniebiz** [comment]
I don't [chew my cabbage twice](https://english.stackexchange.com/questions/473856/origin-of-i-dont-chew-my-cabbage-twice).
