### ISSUE TITLE
requestId overflow

### ISSUE THREAD

**Issue by djpeton** [mongodb-js/mongodb-core#447]
Hi,

In file:
https://github.com/mongodb-js/mongodb-core/blob/d40cb87ad415cfe224ae00d7696fc549fbbd0c62/lib/connection/msg.js#L105

requestId is used to write 2 bytes into header, but there is no limitation on how big this.requestId can be. It is growing with every message:

https://github.com/mongodb-js/mongodb-core/blob/d40cb87ad415cfe224ae00d7696fc549fbbd0c62/lib/connection/msg.js#L133

And so, eventually it will reach maximum allowed value:

As node documentation is saying:

https://nodejs.org/api/buffer.html#buffer_buf_writeint32le_value_offset

value should be a valid signed 32-bit integer. Behavior is undefined when value is anything other than a signed 32-bit integer.

In reality it means error which cannot be fixed even by re-connection to database:
```
TypeError: "value" argument is out of bounds
  at checkInt (buffer.js:1185:11)
  at Buffer.writeInt32LE (buffer.js:1375:5)
  at Msg.toBin (/node_modules/mongodb/node_modules/mongodb-core/lib/connection/msg.js:105:12)
```

**Comment by mbroadst** [comment]
Hi @djpeton, I see [NODE-2067](https://jira.mongodb.org/browse/NODE-2067) was opened for this. I'm going to close this ticket (since issues will shortly be disabled on this repository) in favor of that one. Thanks!
