### ISSUE TITLE
AWS Lamdba Serverless timeouts

### ISSUE THREAD

**Issue by dested** [mongodb-js/mongodb-core#462]
I am having an issue using this package (`"mongodb": "3.4.1"`) to connect to my hosted mongo instance when using AWS Lambda as a serverless api that I am hoping you can shed some light on to. I have tested this with multiple hosting providers with the same results, so the issue is either with this driver or Mongodb itself. 

Throughout the day the lambda will be invoked. Sometimes frequently, sometimes infrequently. I have noticed some (very difficult to reproduce) behavior when my lambdas are warm, meaning after the mongo connection has been established. When I call `mongoClient.isConnected()` it will return true, however my queries will time out for longer than the lambda is allowed to live (which with AWS API Gateway is 30 seconds). I have tried all manor of timeouts with varying levels of success, none addressing the core of the issue. 

I am instianting my client with 
`new MongoClient(connectionString, {useUnifiedTopology: true,useNewUrlParser: true});`

The reason I feel this is a novel issue with regard to serverless is I recently stumbled upon this article (
https://aws.amazon.com/premiumsupport/knowledge-center/lambda-function-retry-timeout-sdk/) which states that open sockets timeout after 120 seconds, which is typically shorter than my lambda is dormant for before it starts up again, still technically a warm start though. 

I have resorted to starting all of my lambda invocations (warm or cold) with a call to `db.command({ping: 1})` that I manually time out after 4 seconds, in which case I force a disconnect and reconnect. While this is working for me, it was rough to arrive at, mostly because `mongoClient.isConnected()` returns an erroneous true. 

I'm truly not sure what the solution to this could be, but perhaps a special config entry for `serverless` which forces the underlying connection to be aware of this 120 second open socket timeout.

**Comment by mbroadst** [comment]
Hi @dested!
I highly recommend upgrading to the v3.5.x series of the driver (currently 3.5.2, with a 3.5.3 release shortly). It introduces a modern connection pool, stream-based connection type and corrects a number of issues with server discovery and monitoring.
